name: nf_sports
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
 
environment:
  sdk: ">=3.2.12"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  image_picker: ^1.1.2
  record: ^7.0.0
  path_provider: ^2.1.2
  path: ^1.9.0
  http: ^1.2.2
  shared_preferences: ^2.2.3
  glass_kit: ^4.0.2
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
<<<<<<< HEAD
  flutter_launcher_icons: "^0.13.1" # 👑 حقن أداة التوليد الأصلية والنظيفة
=======
  flutter_launcher_icons: "^0.13.1"
>>>>>>> 128b556 (Fix and generate app icons)

flutter:
  uses-material-design: true
  assets:
    - assets/images/
<<<<<<< HEAD
    - assets/icons/  # ✅ مسار مجلد أيقونتك الفخمة

# 👑 تفعيل محرك الأيقونات السحري لإعادة بناء كافة مجلدات الأندرويد المحذوفة تلقائياً
=======
    - assets/icons/

>>>>>>> 128b556 (Fix and generate app icons)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/nf_sports_icon.png"
