name: nf_sports
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.12"
 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  image_picker: ^1.1.2
  record: ^7.0.0
  path_provider: ^2.1.2
  path: ^1.9.0
  http: ^1.2.2
  shared_preferences: ^2.2.3
  glass_kit: ^4.0.2
  flutter_inappwebview: ^6.1.5
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/nf_sports_icon.png"
  adaptive_icon_background: "#070D14"
  adaptive_icon_foreground: "assets/icons/nf_sports_icon.png"
